### ISSUE TITLE
Reddit posts are fetched but do not display

### ISSUE THREAD

**Issue by Jamesllllllllll** [Jamesllllllllll/Daily-Dashboard#40]
When running locally with `vercel dev` (vercel cli tool is required to allow serverless functions to work) it seems to fetch reddit posts but they are not displayed.

![Screenshot 2024-01-17 131617](https://github.com/Jamesllllllllll/Daily-Dashboard/assets/125431058/98e3d694-808d-4b70-a570-19935c70dedc)

The generated URL is present, and when clicking a "loading" card it correctly navigates to a dynamically created article page. (example: http://localhost:3000/article/16ocz6d)

On the generated page the article title appears, but nothing else.

It seems this will require looking closely at how the data is fetched and put into state. The changes to the free Reddit API might be a factor as well.

**Comment by Jamesllllllllll** [comment]
The Reddit component was commented out (hidden) in my PR #51 until it is fixed and we can display it again.

**Comment by Jamesllllllllll** [comment]
@klunkyfungus said the reddit posts were fetched correctly when they ran it locally

**Comment by mdwiltfong** [comment]
I've diagnosed this issue [here](https://github.com/Jamesllllllllll/Daily-Dashboard/issues/54) 

I'm exploring whether we will need to use OAuth in order to make these API requests.

**Comment by klunkyfungus** [comment]
Are we ok with closing this out since reddit is out of the picture?
